import streamlit as st
import pandas as pd
from datetime import datetime
from utils.preprocess import load_data
from agent_router import route_query

# Page config
st.set_page_config(page_title="Health AI Assistant", layout="wide")

# Custom CSS
st.markdown("""
    <style>
        body {
            background-color: #f0f8ff;
            color: #222;
        }
        .top-bar {
            background-color: #008080;
            padding: 15px 30px;
            color: white;
            font-weight: bold;
            font-size: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            border-radius: 0 0 10px 10px;
        }
        .stTextInput>div>div>input {
            background-color: #ffffff;
            color: #000000;
            border-radius: 8px;
            padding: 10px;
            border: 2px solid #00cccc;
        }
        .stButton button {
            background-color: #00b894 !important;
            color: white !important;
            border-radius: 10px;
        }
        .stMarkdown h3 {
            color: #006666;
        }
        footer {
            visibility: hidden;
        }
    </style>
""", unsafe_allow_html=True)

# Top Bar
st.markdown('<div class="top-bar">🧬 Personal Health AI Assistant</div>', unsafe_allow_html=True)

# Header
st.markdown("## 💡 Get personalized suggestions from your daily health data")

# Load health dataset
data = load_data()

# Text Query Box
query = st.text_input("🔎 Ask something about your health 👇")

if query:
    with st.spinner("Analyzing your query..."):
        response = route_query(query, data)

    st.markdown("### 🤖 Response")
    st.write(response)

    if "I'm still learning" in response or "You are a personal health assistant" in response:
        st.info("This response was generated by an AI language model via OpenRouter LLM.")

# Form: Daily Health Log
st.markdown("## 📝 Log Today’s Health Data")

with st.form("health_form"):
    date = st.date_input("Date", datetime.today())
    steps = st.slider("Steps Walked", 0, 20000, step=100)
    sleep_hours = st.slider("Hours Slept", 0.0, 12.0, step=0.1)
    mood = st.selectbox("Mood", ["happy", "okay", "sad", "anxious", "neutral"])
    diet_quality = st.selectbox("Diet Quality", ["good", "average", "poor"])
    symptoms = st.text_input("Symptoms (comma-separated)", placeholder="e.g., headache, fatigue")

    submitted = st.form_submit_button("Submit Entry")

    if submitted:
        new_entry = {
            "date": date.strftime("%Y-%m-%d"),
            "steps": steps,
            "sleep_hours": sleep_hours,
            "diet_quality": diet_quality,
            "mood": mood,
            "symptoms": symptoms if symptoms else "None"
        }

        data_path = r'C:\Users\HP-NBT\Desktop\project\AI Agents\Personal Health Agent\data\health_data.csv'
        df = pd.read_csv(data_path)
        df = pd.concat([df, pd.DataFrame([new_entry])], ignore_index=True)
        df.to_csv(data_path, index=False)

        st.success("✅ Entry submitted and saved!")
